title: CULD Wiki
author: Mara Dominguez
remote_theme: abhinavs/moonwalk 
plugins:
- jekyll-remote-theme 

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  appearance_toggle: true # if appearance can be switched by user
  show_navbar: true # show horizontal navbar
